### ISSUE TITLE
Spring cron expression with day of week and day of month wrong next execution

### ISSUE THREAD

**Issue by ms3eed** [jmrozanec/cron-utils#388] opened 2019-07-15 22:30 UTC
**Problem**
On version 8.1.1
With the cron expression like `0 0 8 1-7 * SAT` [check this ](https://cronexpressiondescriptor.azurewebsites.net/?expression=0+0+8+1-7+*+SAT&locale=en).
Where it is assumed to be fired on Saturday in the first week of the month. The next execution is ignoring the day of month. So it is just returning the next Saturday as if the day of month field is a question mark.

```
CronParser springCronParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.SPRING));
Cron quartzCron = springCronParser.parse("0 0 8 1-7 * SAT");
ZonedDateTime now = ZonedDateTime.now();
ExecutionTime executionTime = ExecutionTime.forCron(cron);
Optional<ZonedDateTime> nextExecutionTime = executionTime.nextExecution(now);
Optional<ZonedDateTime> lastExecutionTime = `executionTime.lastExecution(now);
```

Not sure if the Lib is supporting such an expression?

On the other hand when using the Quartz Definition `0 0 8 ? * SAT#1` it gives the correct value but the description is different from the one generated from spring
``` CronParser quartzCronParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
Cron quartzCron = quartzCronParser.parse(generatedExpression);
CronDescriptor cronDescriptor = CronDescriptor.instance();
String cronDescription = cronDescriptor.describe(cron);
String quartzCronDescription = cronDescriptor.describe(quartzCron);
```

**Comment by jmrozanec** [comment] 2019-07-16 05:37
@ms3eed thank you for reporting this! The lib should accurately support any cron definition. May we ask you to submit a PR with a test for the Spring bug? Thanks!

**Comment by ms3eed** [comment] 2019-07-16 09:31
Sure will provide it today.

**Comment by ms3eed** [comment] 2019-07-22 10:23
May I work on this?

**Comment by jmrozanec** [comment] 2019-07-22 10:24
@ms3eed sure - go ahead!

**Comment by alsereda** [comment] 2020-04-30 20:36
The issue with a day-of-week definition. Spring is used "0" for Sunday as it is defined here - https://www.manpagez.com/man/5/crontab/
But CronDefinition.spring() defines it as ".withValidRange(1, 7).withMondayDoWValue(2)", which means that Sunday corresponds to "1".

**Comment by jmrozanec** [comment] 2020-10-11 16:34
@ms3eed the issue is now fixed. Best!

**Closed by jmrozanec** 2020-10-11 16:34 UTC
Labels: bug, hacktoberfest, help wanted
