### ISSUE TITLE
A cron-utils bug by year

### ISSUE THREAD

**Issue by HongZhaoHua** [jmrozanec/cron-utils#430] opened 2020-06-06 08:13 UTC
use cron "0 0 12 30 6 ? 2020/10"

and use dateTime = ZonedDateTime.of(2020, 6, 30, 12, 0, 0, 0, ZoneOffset.UTC);

now, run execution.nextExecution(dateTime);

you will get the result is 2021-6-30T12:00

but in fact, the result must be 2030-6-30T12:00

**Comment by HongZhaoHua** [comment] 2020-06-06 08:17
here is the unit test. plz check it.

    @Test
    public void test() {
        CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
        CronParser parser = new CronParser(cronDefinition);
        ExecutionTime execution = ExecutionTime.forCron(parser.parse("0 0 12 30 6 ? 2020/10"));
        ZonedDateTime dateTime = ZonedDateTime.of(2020, 6, 30, 12, 0, 0, 0, ZoneOffset.UTC);
        {
            Assert.assertEquals(dateTime.minusYears(10), execution.lastExecution(dateTime).orElse(null));
        }
        {
            Assert.assertEquals(dateTime.plusYears(10), execution.nextExecution(dateTime).orElse(null));
        }
    }

**Comment by HongZhaoHua** [comment] 2020-06-06 08:19
@jmrozanec
I hope the bug can be fixed as soon as possible.

**Comment by alexkarpandrus** [comment] 2020-06-19 11:23
I was just going to raise same issue. 
The real issue however is that it seems that step syntax (`n/m`) doesn't work -- it doesn't take into account `n`. 
So, you'd experience same issue with other fields, not only year, hence, I'd suggest to rename the issue to make it more clear.

**Comment by alexkarpandrus** [comment] 2020-06-19 11:33
I'd also point out that I believe the problem is in `EveryFieldValueGenerator`.

` public EveryFieldValueGenerator(final CronField cronField) {
        super(cronField);

        final Every every = (Every) cronField.getExpression();
        final FieldExpression everyExpression = every.getExpression();
        if (everyExpression instanceof Between) {
            final Between between = (Between) everyExpression;

            from = Math.max(cronField.getConstraints().getStartRange(), BetweenFieldValueGenerator.map(between.getFrom()));
            to = Math.min(cronField.getConstraints().getEndRange(), BetweenFieldValueGenerator.map(between.getTo()));
        } else {
            from = cronField.getConstraints().getStartRange();
            to = cronField.getConstraints().getEndRange();
        }
    }`

It doesn't handle the case when the `everyExpression instanceof On`

The fix would be something like 

`
    public EveryFieldValueGenerator(final CronField cronField) {
        super(cronField);

        final Every every = (Every) cronField.getExpression();
        final FieldExpression everyExpression = every.getExpression();
        if (everyExpression instanceof Between) {
            final Between between = (Between) everyExpression;

            from = Math.max(cronField.getConstraints().getStartRange(), BetweenFieldValueGenerator.map(between.getFrom()));
            to = Math.min(cronField.getConstraints().getEndRange(), BetweenFieldValueGenerator.map(between.getTo()));
        } 
		else if(everyExpression instanceof On){
			
			final On on = (On) everyExpression;
			
			from = on.getTime().getValue();
			to = cronField.getConstraints().getEndRange();
		}
		else {
            from = cronField.getConstraints().getStartRange();
            to = cronField.getConstraints().getEndRange();
        }
    }`

Haven't neither compiled nor tested this fix yet though, so could be incorrect

**Comment by jmrozanec** [comment] 2020-07-11 06:29
@HongZhaoHua @alexkarpandrus thank you for pointing this out. We also hope this will be fixed asap - contributions are always welcome! 😄

**Comment by chaudharydeepak** [comment] 2020-10-11 18:36
@jmrozanec - I would like to help if its ok? I saw some code snippets above and I guess thats a good starting point. Let me know. Thank you.

**Comment by jmrozanec** [comment] 2020-10-11 19:10
@chaudharydeepak please, go ahead! Thanks!

**Comment by jmrozanec** [comment] 2020-10-27 11:04
@chaudharydeepak do we have an update on this?

**Comment by jmrozanec** [comment] 2021-10-10 18:56
@IndeedSi thanks! 😄

**Closed** 2021-10-10 19:03 UTC
Labels: bug, help wanted, hacktoberfest
