### ISSUE TITLE
Could cron-utils support x weeks to execute

### ISSUE THREAD

**Issue by Nordlichtwzx** [jmrozanec/cron-utils#525] opened 2022-07-08 08:44 UTC

**Comment by jmrozanec** [comment] 2022-07-08 08:52
@Nordlichtwzx could you provide a more informative description, and perhaps some examples or a test case? 😄  Thanks!

**Comment by jmrozanec** [comment] 2022-07-10 20:19
@Nordlichtwzx may we ask for some additional details regarding this task? If no more details are provided, we will close the issue due to insufficient context. Thanks! 😄

**Comment by Nordlichtwzx** [comment] 2022-07-13 06:49
just like every two weeks wednesdays and Thursdays to execute

**Comment by jmrozanec** [comment] 2022-07-13 07:07
@Nordlichtwzx thanks! 😄

**Comment by Spikhalskiy** [comment] 2022-07-13 23:31
Same as https://github.com/jmrozanec/cron-utils/issues/506

**Comment by jmrozanec** [comment] 2022-07-14 07:15
https://stackoverflow.com/questions/46109358/how-to-create-a-cron-expression-for-every-2-weeks

**Comment by jmrozanec** [comment] 2022-07-14 07:16
Closing as a duplicate of issue #506

**Closed by jmrozanec** 2022-07-14 07:16 UTC
Labels: duplicate
