### ISSUE TITLE
Cairo time zone causing infinite loop for the 27th of April 

### ISSUE THREAD

**Issue by kemalerden** [jmrozanec/cron-utils#324] opened 2018-04-26 13:03 UTC
public static void main(String[] args) {
        CronDefinition cronDefinition =
            CronDefinitionBuilder.defineCron()
                .withSeconds().and()
                .withMinutes().and()
                .withHours().and()
                .withDayOfMonth()
                .supportsHash().supportsL().supportsW().and()
                .withMonth().and()
                .withDayOfWeek()
                .withIntMapping(7, 0)
                .supportsHash().supportsL().supportsW().and()
                .withYear().optional().and()
                .instance();
        CronParser parser = new CronParser(cronDefinition);

        ZoneId zoneIdJo = ZoneId.of("Africa/Johannesburg");
        ZoneId zoneIdCairo = ZoneId.of("Africa/Cairo");
        ZoneId[] zoneIds = new ZoneId[] {zoneIdJo, zoneIdCairo};
        Cron cron = parser.parse("0 0 0 * * *");
        ExecutionTime executionTime = ExecutionTime.forCron(cron);

        for (ZoneId zoneId : zoneIds) {
            ZonedDateTime reference = ZonedDateTime.of(LocalDateTime.of(2018, 4, 27, 23, 0), zoneId);
            System.out.println("reference => " + reference);

            Optional<ZonedDateTime> next = executionTime.nextExecution(reference);
            System.out.println("next => " + next.get());

            System.out.println("next call has bug for Cairo works for Joburg");
            Optional<ZonedDateTime> previous = executionTime.lastExecution(reference);
            System.out.println("previous => " + previous.get());

            System.out.println();

        }

**Comment by jmrozanec** [comment] 2018-04-26 13:05
@kemalerden thank you for reporting this! Won't you mind sending a PR with the test for this case? We will be glad to merge it and start working on a solution. Thanks!

**Comment by Naxos84** [comment] 2018-04-26 13:54
@kemalerden I modified the console outpu a bit and got:

> Testing cron: 'at 00:00'
> reference => 2018-04-27T23:00+02:00[Africa/Johannesburg]
> next execution after reference=> 2018-04-28T00:00+02:00[Africa/Johannesburg]
> next call has bug for Cairo works for Joburg
> previous execution before reference=> 2018-04-27T00:00+02:00[Africa/Johannesburg]
> 
> reference => 2018-04-27T23:00+02:00[Africa/Cairo]
> next execution after reference=> 2018-04-28T00:00+02:00[Africa/Cairo]
> next call has bug for Cairo works for Joburg
> previous execution before reference=> 2018-04-27T00:00+02:00[Africa/Cairo]

What do you expect to be the previous execution before reference?

**Comment by kemalerden** [comment] 2018-04-26 14:37
Hi,
I get an infinite loop at that point using jdk1.8 and cron utils 7.0.1. The call won’t return so it won’t show any output.

**Comment by Naxos84** [comment] 2018-04-26 15:13
@kemalerdem could you please verify with the latest commit from cron-utils master branch?

Cause obviously I don't get any infinite loop (see posted console output).

Thx in advance.

**Comment by kemalerden** [comment] 2018-04-26 16:38
Hi @Naxos84,
It seems to be relevant to the jdk I was using.
jdk1.8.0_40-x64 causes the loop on my machine.
tested on a different machine with jdk1.8.0_66-x64 and it worked.
both windows.
I guess you can close the issue...

PS: the loop seems to be on this value:

ExecutionTimeResult{time=2018-04-27T23:00+03:00[Africa/Cairo], isMatch=false}
ExecutionTimeResult{time=2018-04-27T23:00+03:00[Africa/Cairo], isMatch=false}
ExecutionTimeResult{time=2018-04-27T23:00+03:00[Africa/Cairo], isMatch=false}
...

**Comment by jmrozanec** [comment] 2018-04-26 17:47
@kemalerden @Naxos84 thank you both for such a quick response! Shall we close the issue?

**Comment by Naxos84** [comment] 2018-04-26 19:17
I'm curious why this happens with this java version.

But yes you can close it for now.

**Comment by kemalerden** [comment] 2018-04-27 08:51
@Naxos84 
Thanks for looking into this.
seeing same issue on jdk1.8.0_45-x64 on a linux box as well - maybe a fix was made on java timezones, zoneIds on a later version?
can be closed from my side...

**Comment by jmrozanec** [comment] 2018-06-05 02:05
Duplicate of #329

**Closed** 2018-06-05 02:04 UTC
Labels: bug, done, duplicate
