### ISSUE TITLE
cron-utils fails to describe weekday list

### ISSUE THREAD

**Issue by PrasadaRaoK** [jmrozanec/cron-utils#39] opened 2015-09-08 13:59 UTC
When we select cron expression as weekly Monday and Tuesday the expression is coming like 
0 0 0 ? * MON,TUE *

exception got while parsing the cron expression.

in hours tab 
![image](https://cloud.githubusercontent.com/assets/14180835/9736604/cf2dfbec-565f-11e5-9802-2425c59b2dd3.png)

![image](https://cloud.githubusercontent.com/assets/14180835/9736617/e5b9a53c-565f-11e5-9084-c9272c1a28df.png)

**Comment by jmrozanec** [comment] 2015-09-09 01:29
@PrasadaRaoK Thank you for using cron-utils! May I ask you for a test to reproduce the issue? I am unable to reproduce it for now. Below I paste the test I created:

CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
parser.parse("0 0 0 ? * MON,TUE *");
//works as expected

**Comment by jmrozanec** [comment] 2015-09-11 12:07
@PrasadaRaoK Please provide a test to reproduce the issue. Otherwise we will close the issue as unable to reproduce. Thank you!

**Comment by PrasadaRaoK** [comment] 2015-09-11 14:14
I used the below code to parse the expression "0 0 0 ? * MON,TUE *"

I tried with your code also 
CronParser parser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));

----


CronDefinition cronDefinition = CronDefinitionBuilder.defineCron()
                    .withSeconds().and()
                    .withMinutes().and()
                    .withHours().and()
                    .withDayOfMonth()
                        .supportsHash().supportsL().supportsLW().supportsW().supportsQuestionMark().and()
                    .withMonth().and()
                    .withDayOfWeek()
                        .withMondayDoWValue(1)
                        .withIntMapping(7, 0)
                        .supportsHash().supportsL().supportsLW().supportsW().supportsQuestionMark().and()
                    .withYear().and()
                    .lastFieldOptional()
                    .instance();

            CronParser parser = new CronParser(cronDefinition);
            Cron quartzCron = parser.parse(cronExpression);
            CronDescriptor descriptor = CronDescriptor.instance(Locale.ENGLISH);
            readableExpression = descriptor.describe(quartzCron);

**Comment by jmrozanec** [comment] 2015-09-11 20:39
@PrasadaRaoK Thank you for providing the example. I was able to reproduce it and created a test for it. The issue happens when describing the cron pattern. I found where it lays; still need to find a good way to fix this.

**Comment by jmrozanec** [comment] 2015-12-21 10:15
@PrasadaRaoK Issue fixed!

**Closed by jmrozanec** 2015-12-21 10:15 UTC
Labels: bug, helpwanted
