### ISSUE TITLE
IllegalArgumentException for valid spring cron expression

### ISSUE THREAD

**Issue by toughpheeckouse** [jmrozanec/cron-utils#343] opened 2018-09-22 19:00 UTC
I got sample expressions from docs of org.springframework.scheduling.support.CronSequenceGenerator class and try to get description of these expressions by CronDefinitionBuilder.instanceDefinitionFor(CronType.SPRING).
After that I've got exception Both, a day-of-week AND a day-of-month parameter, are not supported.

this is test case

```java
package ru.rencredit.budgetcontrol.test.cronutils;

import java.util.Locale;

import org.hamcrest.core.IsEqual;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import com.cronutils.descriptor.CronDescriptor;
import com.cronutils.model.CronType;
import com.cronutils.model.definition.CronDefinition;
import com.cronutils.model.definition.CronDefinitionBuilder;
import com.cronutils.parser.CronParser;

@RunWith(Parameterized.class)
public class CronUtilsTest
{
	@Parameters
	public static Object[] expressions()
	{
		return new Object[] {
				new Expr("0 0 * * * *", "every hour"),
				new Expr("*/10 * * * * *", "every 10 seconds"),
				new Expr("0 0 8-10 * * *", "every hour between 8 and 10"),
				new Expr("0 0 6,19 * * *", "at 6 and 19 hours"),
				new Expr("0 0/30 8-10 * * *", "every 30 minutes every hour between 8 and 10"),
				new Expr("0 0 9-17 * * MON-FRI", "every hour between 9 and 17 every day between Monday and Friday"),
				new Expr("0 0 0 25 12 ?", "at 00:00 at 25 day at December month")
		};
	}
	
	private Expr expressionToTest;
	
	public CronUtilsTest(Expr expressionToTest)
	{
		this.expressionToTest = expressionToTest;
	}
	
	@Test()
	public void test()
	{
		CronParser pareser = new CronParser( CronDefinitionBuilder.instanceDefinitionFor(CronType.SPRING) );
		
		String actualDescription = CronDescriptor.instance(Locale.ENGLISH).describe(pareser.parse(expressionToTest.getExpression()));
		
		Assert.assertThat(actualDescription, IsEqual.equalTo(expressionToTest.getDescription()));
	}
	
	
	private static class Expr
	{
		private final String expression;
		private final String description;
		
		public Expr(String expression, String description)
		{
			super();
			this.expression = expression;
			this.description = description;
		}
		public String getExpression()
		{
			return expression;
		}
		public String getDescription()
		{
			return description;
		}
	}
}

```

**Comment by jmrozanec** [comment] 2018-09-23 07:28
@toughpheeckouse thank you for reporting this. May we ask you to submit a PR with the code above? Most probably this can be fixed with a custom expression definition. Thanks!

**Comment by NielsDoucet** [comment] 2019-03-08 12:38
This seems to be caused by the fix for #63 
If I remove `.withCronValidation(CronConstraintsFactory.ensureEitherDayOfWeekOrDayOfMonth())` from the CronDefinition for type spring all these examples pass.

**Comment by jmrozanec** [comment] 2019-03-08 23:35
@NielsDoucet thank you for this insight! Can we work on getting a fix for this? Thanks! 😄

**Comment by NielsDoucet** [comment] 2019-03-10 20:36
hey @jmrozanec 
I didn't have time to create a PR for this during this week-end, but I'll try to get something prepared soon (hopefully by the end of the week).

**Comment by jmrozanec** [comment] 2019-03-11 08:58
@NielsDoucet great! Thanks! 😄

**Closed** 2019-03-11 21:03 UTC
Labels: bug, hacktoberfest, help wanted

**Comment by jmrozanec** [comment] 2019-06-18 09:01
@toughpheeckouse @NielsDoucet  a [new release](https://github.com/jmrozanec/cron-utils/milestone/17) is available with this changes. Best!
