### ISSUE TITLE
ExecutionTime.nextExecution() causes infinite loop for non-existent dates

### ISSUE THREAD

**Issue by catharsis** [jmrozanec/cron-utils#329] opened 2018-05-16 15:13 UTC
Reproduced by:
```
  @Test
  public void infiniteLoop() {
    Cron cron = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX))
      .parse("0 0 30 2 *");
    ExecutionTime.forCron(cron).nextExecution(ZonedDateTime.now());
  }
```

**Comment by jmrozanec** [comment] 2018-05-17 06:18
@catharsis thank you for reporting this. We just merged the test to master, but we are unable to reproduce the issue. May we ask for the version you are working on? Maybe the issue was solved. Thanks!

**Comment by catharsis** [comment] 2018-05-17 06:56
@jmrozanec Interesting! I'm on `7.0.1`, which I believe is the latest released version (though I'd be happy to hear I'm wrong about this :smile:).

**Comment by jmrozanec** [comment] 2018-05-17 06:59
@catharsis perhaps a change we introduced for 7.0.2 fixes the issue. Will keep you posted when we release the new version! Thanks!

**Closed** 2018-05-17 06:59 UTC
Labels: bug, done

**Comment by Naxos84** [comment] 2018-05-17 07:59
What is your time zone when executing the infinite loop test.

jmrozanec <notifications@github.com> schrieb am Do., 17. Mai 2018, 08:59:

**Comment by catharsis** [comment] 2018-05-17 08:06
@Naxos84 I'm currently at `CEST`, though I don't think any time zone will ever see a 30th of February(?).

This test has the same behavior as the one in the original report, for example:
```
  @Test
  public void infiniteLoopInUTC() {
    Cron cron = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.UNIX))
      .parse("0 0 30 2 *");
    ExecutionTime.forCron(cron).nextExecution(LocalDateTime.now().atZone(ZoneId.of("UTC")));
  }
```

**Comment by catharsis** [comment] 2018-05-17 08:11
@jmrozanec skimming the log since `7.0.1`, I found commit https://github.com/jmrozanec/cron-utils/commit/7a0565dcf48cf65773a6ebf476f4a3bfa38205a4, which presumably is why our experiences differ. Do you have any plans to do a new release any time soon?

**Comment by jmrozanec** [comment] 2018-05-17 08:11
@Naxos84 @catharsis I think was solved with [this fix](https://github.com/jmrozanec/cron-utils/pull/311)

**Comment by jmrozanec** [comment] 2018-05-17 08:13
@catharsis we had some issues releasing a new version. Will work on it and deliver by monday. Will post an update when released.

**Comment by catharsis** [comment] 2018-05-17 08:14
Yup, this is a duplicate of https://github.com/jmrozanec/cron-utils/issues/310. Sorry, I should've looked through the closed issues before posting a new issue :disappointed:

**Comment by jmrozanec** [comment] 2018-05-17 08:25
@catharsis no worries! Thanks for reaching out! We have one more reason to release asap 😄

**Comment by Naxos84** [comment] 2018-05-17 17:17
Sorry. I read to fast and didn't see that it was the 30th of February:-D

jmrozanec <notifications@github.com> schrieb am Do., 17. Mai 2018, 10:25:

**Comment by jmrozanec** [comment] 2018-06-02 13:38
@catharsis @Naxos84  release 7.0.2 is now available! Thank you for contributing to cron-utils!
