### ISSUE TITLE
java.lang.NoClassDefFoundError com/google/common/collect/Maps

### ISSUE THREAD

**Issue by mhashem** [jmrozanec/cron-utils#17] opened 2015-05-12 21:16 UTC
Hello there, I am using the jar file from maven central [cron-utils-1.1.2.jar](http://mvnrepository.com/artifact/com.cronutils/cron-utils/1.1.2)

this is my code following the examples :

```
package com.mh.cronParser;

import com.cronutils.descriptor.CronDescriptor;
import com.cronutils.model.Cron;
import com.cronutils.model.CronType;
import com.cronutils.model.definition.CronDefinition;
import com.cronutils.model.definition.CronDefinitionBuilder;
import com.cronutils.parser.CronParser;
import com.cronutils.validator.CronValidator;

import java.util.Locale;

public class Main {

    public static void main(String[] args) {
        CronDefinition cronDefinition =
                CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);

        //create a parser based on provided definition
        CronParser parser = new CronParser(cronDefinition);
        Cron quartzCron = parser.parse("0 23 ? * * 1-5 *");
        System.out.println(quartzCron.asString());

        //create a descriptor for a specific Locale
        CronDescriptor descriptor = CronDescriptor.instance(Locale.UK);

        //parse some expression and ask descriptor for description
        String description = descriptor.describe(parser.parse("*/45 * * * * *"));
        //description will be: "every 45 seconds"

        //Validate if a string expression matches a cron definition:
        CronValidator quartzValidator = new CronValidator(cronDefinition);

        //getting a boolean result:
        quartzValidator.isValid("0 23 ? * * MON-FRI *");

        //or returning same string if valid and raising an exception if invalid
        quartzValidator.validate("0 23 ? * * MON-FRI *");
    }
}

```

and I got this exception when I tried to run the program

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Maps
	at com.cronutils.model.definition.CronDefinitionBuilder.<init>(CronDefinitionBuilder.java:39)
	at com.cronutils.model.definition.CronDefinitionBuilder.defineCron(CronDefinitionBuilder.java:48)
	at com.cronutils.model.definition.CronDefinitionBuilder.quartz(CronDefinitionBuilder.java:152)
	at com.cronutils.model.definition.CronDefinitionBuilder.instanceDefinitionFor(CronDefinitionBuilder.java:188)
	at com.mh.cronParser.Main.main(Main.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 10 more
```

looks like the built jar is not fine

**Comment by jmrozanec** [comment] 2015-05-13 13:03
Thank you for reporting this. I created a brand new maven project, putting just the cron-utils:1.1.2 dependency, copied your main class, executed and it works. 
Please provide more details and means to reproduce it, do that I can provide further help.

**Comment by jmrozanec** [comment] 2015-05-13 23:25
Closing unable to reproduce. cron-utils:1.1.2 as the only dependency on a project does not present the issues described.

**Closed by jmrozanec** 2015-05-13 23:26 UTC
Labels: UTR
