### ISSUE TITLE
ExecutionTime.isMatch() doesn't work when year is specified

### ISSUE THREAD

**Issue by johnchurin** [jmrozanec/cron-utils#470] opened 2021-03-24 06:18 UTC
**Expected behavior:**  A supplied date of midnight, march 23, 2021 should match a Quartz pattern of "0 0 0 23 3 ? 2021". 
**Observed behavior:** If the supplied date exactly matches the pattern, then ExecutionTime.isMatch() returns false rather than true.

**Analysis:** The cause of the problem seems obvious looking at the implementation in SingleExecutionTime:
```
public boolean isMatch(ZonedDateTime date) {
        ...
        if (last.isPresent()) {
        ...
        }
        return false;
```

In other words, if there is no date occurrence before now, then "now" can never match the pattern, even if it's an exact match!

**Evidence:** I've attached a unit test which shows patterns with and without a year specified, the latter of which works as expected because there will always be an occurrence before (and after) the "now" date.

The relevant parts of the test:
```
	@Test
	public void testWithYearInPattern() {
		ZonedDateTime dt = ZonedDateTime.of(2021, 3, 23, 0, 0, 0, 0, ZoneId.of("UTC"));
		CronDefinition cd = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
		CronParser parser = new CronParser(cd);
		Cron cron = parser.parse("0 0 0 23 3 ? 2021");
		cron.validate();
		System.out.println(cron.asString());
		ExecutionTime et1 = ExecutionTime.forCron(cron);
		...
		assert(et1.isMatch(dt));// Fails in 9.1.3
	}

```
[TestIsMatch.java.txt](https://github.com/jmrozanec/cron-utils/files/6194766/TestIsMatch.java.txt)

**Comment by jmrozanec** [comment] 2021-03-24 07:12
@johnchurin thank you for reporting this. Could you please send a PR with the test? Thanks!

**Comment by jmrozanec** [comment] 2021-03-29 11:06
@johnchurin thank you for the insights! The issue is fixed and a fixed version will be released soon! 😄

**Closed by jmrozanec** 2021-03-29 11:06 UTC
Labels: bug, help wanted

**Comment by jmrozanec** [comment] 2021-04-01 15:25
@johnchurin a new release was published with the fix!
