### ISSUE TITLE
NextExecution calculates wrong time

### ISSUE THREAD

**Issue by gokhanoner** [jmrozanec/cron-utils#24] opened 2015-06-15 12:29 UTC
Sample cron expression

    0 0/10 22 * * *

I run the core at 15:27, and it gives me the next execution time of 22:30, which should be 22:00. I believe it first look to the minute than hours, so next close value in range to 27 is 30.

İt should look first to year, month, etc, starting from bigger to smaller time unit.

**Comment by jmrozanec** [comment] 2015-06-16 02:38
@gokhanoner thank you for reporting this. I will take a look at this. We may need to rethink how is this done today. Current logic was thought taking keeping in mind that ex.: if we have more than 60 minutes, then we would need to shift hours. Perhaps looking from bigger to smaller unit and then applying required shifts would solve the issue.
Please let me know any thoughts you may have on this!

**Comment by jmrozanec** [comment] 2015-06-16 02:39
Test case for this issue:

/**
     * Issue #24: next execution not properly calculated
     */
    @Test
    public void testTimeShiftingProperlyDone() throws Exception {
        ExecutionTime executionTime = ExecutionTime.forCron(quartzCronParser.parse("0 0/10 22 * * *"));
        DateTime nextExecution =
                executionTime.nextExecution(
                        DateTime.now()
                                .withHourOfDay(15)
                                .withMinuteOfHour(27)
                );
        assertEquals(22, nextExecution.getHourOfDay());
        assertEquals(0, nextExecution.getMinuteOfHour());
    }

**Comment by jmrozanec** [comment] 2015-06-18 12:28
@gokhanoner The issue is fixed now! As part of the fix, nextExecution calculation was greatly simplified.
A new release with fixes will be uploaded to Maven central this weekend. Thank you for reporting!

**Closed by jmrozanec** 2015-06-18 12:28 UTC
Labels: bug
