### ISSUE TITLE
Quartz Cron Year Pattern is not fully supported - i.e. increments on years are not supported

### ISSUE THREAD

**Issue by meincs** [jmrozanec/cron-utils#154] opened 2017-02-20 17:38 UTC
The Quartz cron expression specification allows increments for the year field, see
http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger

e.g. 
even years starting from 2017, year field => 2018/2
even years starting from 2017 until 2027 => 2018-2026/2
every decade starting from 2017,  year field => 2017/10

Currently the use of yearly increments results in an exception:

```java
Exception in thread "main" java.lang.IllegalArgumentException: Failed to parse '0 0 0 ? * 1 2017/10'. Value 10 not in range [1970, 2099]
	at com.cronutils.parser.CronParser.parse(CronParser.java:95)
Caused by: java.lang.IllegalArgumentException: Value 10 not in range [1970, 2099]
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.isInRange(ValidationFieldExpressionVisitor.java:152)
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:119)
	at com.cronutils.model.field.expression.visitor.ValidationFieldExpressionVisitor.visit(ValidationFieldExpressionVisitor.java:60)
	at com.cronutils.model.field.expression.FieldExpression.accept(FieldExpression.java:42)
	at com.cronutils.model.Cron.validate(Cron.java:81)
	at com.cronutils.parser.CronParser.parse(CronParser.java:93)
	... 2 more
```

**Comment by jmrozanec** [comment] 2017-02-20 22:33
@meincs thank you for reporting this. May we ask you to contribute a test for this bug? We will be eager to merge it back to master. Thanks!

**Comment by meincs** [comment] 2017-02-21 10:39
```java
   @Test
    public void supportQuartzCronExpressionIncrementsOnYears() {
        final String[] sampleCronExpressions = {
                "0 0 0 1 * ? 2017/2",
                "0 0 0 1 * ? 2017/3",
                "0 0 0 1 * ? 2017/10",
                "0 0 0 1 * ? 2017-2047/2",
        };

        final CronParser quartzCronParser = new CronParser(CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ));
        try {
            for (final String cronExpression: sampleCronExpressions) {
                final Cron quartzCron = quartzCronParser.parse(cronExpression);
                quartzCron.validate();
            }
        }
        catch (final IllegalArgumentException exceptionNotToThrow) {
            fail("WHOOPS! Threw IllegalArgumentException: " + exceptionNotToThrow.getMessage());
        }
    }
```

If parsing no longer fails, additional tests on semantics can be provided.

**Comment by jmrozanec** [comment] 2017-03-11 04:41
@meincs seems to be a duplicate of #148. Will close this one and continue on the original report issue.

**Closed by jmrozanec** 2017-03-11 04:41 UTC
Labels: bug, contributions welcome
