### ISSUE TITLE
Time zone handling of CRON expressions

### ISSUE THREAD

**Issue by mattadamson** [jmrozanec/cron-utils#321] opened 2018-04-05 16:20 UTC
All,

I realised this might not be the sole responsibility of the cron utils library however I'd appreciate others input on how they might handle this. Typically we'd have code such as 

		final ZonedDateTime now = ZonedDateTime.now(ZoneOffset.UTC);
		final CronParser cronParser = new CronParser(cronDefinition);
		final Cron scheduleFrequencyCron = cronParser.parse(exportScheduleFrequency);
		final ExecutionTime executionTime = ExecutionTime.forCron(scheduleFrequencyCron);
		final Optional<ZonedDateTime> nextExecution = executionTime.nextExecution(now);

If you were provided a CRON expression in the EST format i.e.

0 0 16 * * ? *

How would you usually determine when the next execution is from the servers time?

Thanks

**Comment by jmrozanec** [comment] 2018-04-05 16:29
@mattadamson glad you ask this! Usually, a cron refers to a pattern and will execute against local time - has no knowledge of different time zones. #243 requests migrating a cron from local to another time zone. Would that help on this feature? By migrating the expression to servers time and requesting next execution in servers timezone, should return the required time (and could be eventually converted back to local timezone).

**Comment by jmrozanec** [comment] 2018-07-12 14:01
@mattadamson This will be considered as a duplicate of #243 
We think of two possible cases: 
- migrating the cron to another timezone (a feature we are willing to develop)
- adapting local time to servers timezone in order to compute accurate data (a computation every user can do and does not require further development from our side)
Thanks!

**Closed by jmrozanec** 2018-07-12 14:01 UTC
Labels: feature, help wanted
