### ISSUE TITLE
nextExecution not working for '0/30 * * * * *'

### ISSUE THREAD

**Issue by strmer15** [jmrozanec/cron-utils#37] opened 2015-08-28 17:52 UTC
For the cron expression 0/30 * * * * *, with a custom definition of:

// Unix Crontab with seconds allowed
CronDefinition cronDefinition = CronDefinitionBuilder.defineCron()
                .withSeconds().and()
                .withMinutes().and()
                .withHours().and()
                .withDayOfMonth().and()
                .withMonth().and()
                .withDayOfWeek().withValidRange(0, 7).withMondayDoWValue(1).withIntMapping(7, 0).and()
                .instance();

Performing a nextExecution call when the input DateTime value is between 30 and 59 seconds of the minute causes the method to return with a DateTime at the previous minute instead of the next minute.

For example:

nextExecution('2015-08-28 12:05:44') -> 2015-08-28 12:05:00
nextExecution('2015-08-28 12:05:14') -> 2015-08-28 12:05:30

Note that I've also tried this with '*/30 * * * * *' and got the same results.

Unit tests:

    @Test
    public void testCronExpressionAfterHalf() {

        CronDefinition cronDefinition = CronDefinitionBuilder.defineCron()
                .withSeconds().and()
                .withMinutes().and()
                .withHours().and()
                .withDayOfMonth().and()
                .withMonth().and()
                .withDayOfWeek().withValidRange(0, 7).withMondayDoWValue(1).withIntMapping(7, 0).and()
                .instance();

        CronParser parser = new CronParser(cronDefinition);
        Cron cron = parser.parse("*/30 * * * * *");

        MutableDateTime mutableDateTime = new MutableDateTime();
        mutableDateTime.setDateTime(2015, 8, 28, 12, 5, 44, 0);

        DateTime startDateTime = mutableDateTime.toDateTime();

        mutableDateTime = new MutableDateTime();
        mutableDateTime.setDateTime(2015, 8, 28, 12, 6, 0, 0);

        DateTime expectedDateTime = mutableDateTime.toDateTime();

        ExecutionTime executionTime = ExecutionTime.forCron(cron);

        DateTime nextExecutionDateTime = executionTime.nextExecution(startDateTime);
        MatcherAssert.assertThat(nextExecutionDateTime, Matchers.equalTo(expectedDateTime));
    }

    @Test
    public void testCronExpressionBeforeHalf() {

        CronDefinition cronDefinition = CronDefinitionBuilder.defineCron()
                .withSeconds().and()
                .withMinutes().and()
                .withHours().and()
                .withDayOfMonth().and()
                .withMonth().and()
                .withDayOfWeek().withValidRange(0, 7).withMondayDoWValue(1).withIntMapping(7, 0).and()
                .instance();

        CronParser parser = new CronParser(cronDefinition);
        Cron cron = parser.parse("0/30 * * * * *");

        MutableDateTime mutableDateTime = new MutableDateTime();
        mutableDateTime.setDateTime(2015, 8, 28, 12, 5, 14, 0);

        DateTime startDateTime = mutableDateTime.toDateTime();

        mutableDateTime = new MutableDateTime();
        mutableDateTime.setDateTime(2015, 8, 28, 12, 5, 30, 0);

        DateTime expectedDateTime = mutableDateTime.toDateTime();

        ExecutionTime executionTime = ExecutionTime.forCron(cron);

        DateTime nextExecutionDateTime = executionTime.nextExecution(startDateTime);
        MatcherAssert.assertThat(nextExecutionDateTime, Matchers.equalTo(expectedDateTime));
    }

**Comment by jmrozanec** [comment] 2015-08-31 20:39
@strmer15 Thank you for reporting this! This is a bug. I am digging into the code and looking for a solution. Will keep you updated on changes!

**Comment by paulhethmon** [comment] 2015-10-07 20:35
So I've run into this issue as well and can reproduce it with a unix cron expression for minutes or hours:

0/15 * * * *
0 0/2 * * *

Both of those have the problem. 

The problem appears to be in either ExecutionTime or TimeNode. The root cause is that we have a current time that is the last time in the list. So for the minutes case above, the list of minute values contains 0, 15, 30, and 45. As ExecutionTime.nextClosestMatch runs it finds that value in the list and that reference value is 45. Logic says it rounds up the input time to be the next whole minute. So something like 16:45:01 becomes 16:46:00. That happens in the if statement for seconds. Good so far.

It then recurses with the new date. So minute 46 is not found in the list of minute values. At this point, there is a call to minutes.getNextValue(date.getMinuteOfHour(), 0). This class/method is where the logic problem is evident (though I am not positive it's the only logic problem). So there in the TimeNode class we end up the getNearestForwardValue method. The input value of 46 is not in the list of values (0,15,30,45) so it tries to find a value in the list that is greater. Obviously not there.

The logic then is to increment shiftsToApply, with an intention of getting the next value past the index. The code actually does that, but its the wrong value. The method will return 15 as the next value past 46, when 0 is the proper value. That is due to the shiftsToApply having a value of 1, so the loop at the end skips past the 0 value (which is the current value) and instead picks the next value of 15.

Occam's razor says to just not increment the shiftsToApply value, which I tried, but that causes a couple of the test cases to fail during compile. So that's why I'm not sure the logic bug is in here. I think it is because the next value should be 0 from this method.

I'm going to continue to debug and look for a fix since I picked up this library for a scheduler and need it to handle these cases in particular. Reporting here in case it might be enough for someone more familiar with the library to know where it should be fixed.

I do suspect this same logic bug applies to some of the other open issues as well.

**Comment by paulhethmon** [comment] 2015-10-07 21:50
I think this is a two part fix. Part one is not incrementing shiftsToApply in the TimeNode method as I mentioned before. Part 2 is allowing for time wrap in the ExecutionTime.nextClosestMatch method. So here is my modified check for months:

```java
        if(!months.getValues().contains(date.getMonthOfYear())) {
            log.debug(" == checking months ==");
            nearestValue = months.getNextValue(date.getMonthOfYear(), 0);
            int nextMonths = nearestValue.getValue();
            if(nearestValue.getShifts()>0){
                newDate =
                        new DateTime(date.getYear(), 1, 1, 0, 0, 0).plusYears(nearestValue.getShifts());
                return nextClosestMatch(newDate);
            }
            if (nearestValue.getValue() < date.getMonthOfYear()) {
            	System.out.println("Adding 1 year. near = [" + nearestValue.getValue() + "]" );
            	date = date.plusYears(1);
            }
            log.debug(" == months ==");
            return initDateTime(date.getYear(), nextMonths, lowestDay, lowestHour, lowestMinute, lowestSecond);
        }
```

I've left my debug in there but essentially that last if statement I added recognizes that time has wrapped to the next increment, in this case, next year, and then adds 1 year to it. So this handles the case where the current month is 12 and the next month to execute is 1 (which means next year). Similar cases for the other date components are needed.

However, this still leaves another bug. In the test class ExecutionTimeCron4jIntegrationTest and method testDayOfWeekOverridesAlwaysAtDayOfMonth with the EVERY_MONDAY_AT_18 expression, the calculated days of the month is wrong. With today being 2015-10-07, it only lists day 5 as a Monday. It misses days 12, 19, and 26 in the list. So everything is thrown off.

That's next on my list to track down.

**Comment by jmrozanec** [comment] 2015-10-08 02:15
@paulhethmon thank you for the insight and proposed partial fix! The diagnose is correct - I fully agree with it. There is a bug in the logic about how the shifts and counts are applied. Apart from considering each field on its own; we may find helpful to add more detailed tests on TimeNode shifts behavior. These may give us some insight on cases we are not considering right now; and that propagate the error when calculating values for specific fields.

**Comment by paulhethmon** [comment] 2015-10-08 15:19
@jmrozanec The bug for days of week calculation is in the new method OnDayOfWeekValueGenerator.generateNoneValues(). The return statement with division using integers does not return successive values. I haven't delved into the issues for why you added this method back in August, but its definitely part of the problem. I think I can come up with a fix for this as well as the other things I've found. I will create a pull request once I have but I do have concerns that some of my fixes will impact other things I don't understand.

**Comment by jmrozanec** [comment] 2015-10-08 15:50
@paulhethmon thank you! I will be happy to review the pull request and check how may affect the rest of the codebase before merging it into master.
The changes introduced in August were aiming to replace a previous version of how to compute next/previous executions, which had more issues and was harder to understand.

**Comment by paulhethmon** [comment] 2015-10-09 20:03
@jmrozanec Once I figure out how to actually create a pull request, I will do so. I have some cases fixed, but I know of some that are not, and some edge cases my fixes don't handle.

**Comment by jmrozanec** [comment] 2015-10-09 20:21
@paulhethmon let me know if I can help you some way. If necessary, we can chat at [gitter.im](https://gitter.im/jmrozanec/cron-utils)

**Comment by paulhethmon** [comment] 2015-10-12 13:22
@jmrozanec I think I've created the pull request for issues 37 and 38. It might also help out some of the others. One of the biggest changes was adding a new class BetweenDayOfWeekValueGenerator which handles the day of week range calculations. That class does not handle all cases though. Some of the abstract methods are not implemented as I was not exactly sure about what to do. What I have done does pass several new test cases that I had as well as what was in the issue.

**Comment by jmrozanec** [comment] 2015-10-12 15:23
@paulhethmon I will soon review this pull request, and merge into trunk. Thank you!

**Comment by danielsteenblik** [comment] 2015-10-14 22:07
Hi, this fix would be most welcome for me as well. We are getting nextExecution times in the past with a variety of cron definitions, most recently: */10 * * * *
Thanks!

**Comment by jmrozanec** [comment] 2015-10-15 03:15
@paulhethmon Thank you for providing the fix! I tested it against some other open issues, and seems to fix this and other reported bugs. Will merge into master and release soon a new version with this changes.

**Comment by jmrozanec** [comment] 2015-10-15 03:27
@danielsteenblik we considered the case you expose and verified is solved by the new fix we are introducing. Before weekend a new version of cron-utils will be released to Maven central. Thank you for exposing new cases!

**Comment by jmrozanec** [comment] 2015-10-15 03:28
@strmer15 the issue was fixed! Will release a new version of cron-utils before weekend.

**Closed by jmrozanec** 2015-10-15 03:28 UTC
Labels: bug, helpwanted

**Comment by danielsteenblik** [comment] 2015-10-15 03:48
Great, thanks!

**Comment by danielsteenblik** [comment] 2015-10-19 16:41
Hi @jmrozanec, were you able to make any progress toward a cron-utils
release with these updates? Thanks! -daniel

**Comment by jmrozanec** [comment] 2015-10-19 23:48
@paulhethmon @strmer15 @danielsteenblik [Version 3.1.1](https://github.com/jmrozanec/cron-utils/releases/tag/3.1.1) was released including this fix. 
@paulhethmon thank you for solving this issue!

**Comment by danielsteenblik** [comment] 2015-10-20 00:12
Thank you!

**Comment by jmrozanec** [comment] 2015-10-20 01:01
@danielsteenblik you are welcome! Join us on [Gitter](https://gitter.im/jmrozanec/cron-utils), to stay tuned about updates on future releases!
