### ISSUE TITLE
A cron-utils bug by week

### ISSUE THREAD

**Issue by HongZhaoHua** [jmrozanec/cron-utils#424] opened 2020-04-27 04:51 UTC
use cron "0 0 12 ? * SUN#4 2020"

and use dateTime = ZonedDateTime.of(2021, 1, 1, 0, 0, 0, ZoneOffset.UTC);

now, run execution.lastExecution(dateTime);

you will get the result is 2022-11-27T12:00

but in fact, the  result  must be 2020-12-27T12:00

**Comment by jmrozanec** [comment] 2020-04-27 06:15
@HongZhaoHua thank you for reporting this. May we ask you a PR with a test? Thanks!

**Comment by HongZhaoHua** [comment] 2020-04-27 06:26
@jmrozanec sure.

here is the test, plz check it.

    @Test
    public void test() {
        CronDefinition cronDefinition = CronDefinitionBuilder.instanceDefinitionFor(CronType.QUARTZ);
        CronParser parser = new CronParser(cronDefinition);
        ExecutionTime execution = ExecutionTime.forCron(parser.parse("0 0 12 ? * SUN#4 2020"));
        LocalDate date = LocalDate.of(2021, 1, 1);
        LocalTime time = LocalTime.of(0, 0, 0);
        ZonedDateTime dateTime = ZonedDateTime.of(date, time, ZoneOffset.UTC);
        for (int index = 0, size = 12; index < size; index++) {
            dateTime = execution.lastExecution(dateTime).orElse(null);
            Assert.assertEquals(LocalDateTime.of(2020, 12 - index, 1, 12, 0, 0).with(TemporalAdjusters.dayOfWeekInMonth(4, DayOfWeek.SUNDAY)), dateTime.toLocalDateTime());
        }
    }

**Comment by jmrozanec** [comment] 2020-04-27 06:33
@HongZhaoHua thanks! 😄

**Comment by HongZhaoHua** [comment] 2020-04-27 06:37
@jmrozanec  u r welcome.
^^

**Comment by jmrozanec** [comment] 2020-10-12 14:59
@HongZhaoHua the issue is now fixed!

**Closed** 2020-10-12 14:58 UTC
Labels: bug, hacktoberfest, help wanted
